FROM node:7.0.0
COPY resolv.conf /etc/resolv.conf
COPY sources.list /etc/apt/sources.list
RUN apt-get update
RUN apt-get install -y --force-yes git curl wget screen nano bash
RUN npm config set user root -g
RUN curl -sL https://raw.githubusercontent.com/slap-editor/slap/master/install.sh | sh
#RUN npm install -g npm
RUN npm install -g slap@latest
RUN rm -rf /usr/local/lib/node_modules/slap/node_modules/copy-paste
RUN cd /usr/local/lib/node_modules/slap; npm install copy-paste@1.3.0
RUN cd /root
COPY prompt /root/prompt
COPY bashrc /root/.bashrc
WORKDIR /root
ENTRYPOINT ["tail","-f","/dev/null"]
