FROM node:22.13-alpine3.21
RUN apk update
RUN apk add git curl wget screen mc nano vim micro bash
RUN npm install -g @boutell/tome
RUN npm install -g pnpm
RUN cd /root; git clone https://github.com/MahmoudEl3bady/tedi.git
RUN cd /root/tedi; pnpm install
RUN alias tedi="pnpm dev "
RUN cd /root; git clone https://github.com/goldfiction/gqdn.git
RUN cd /root/gqdn; npm install
RUN cd /root
COPY prompt /root/prompt
COPY bashrc /root/.bashrc
COPY tedialias /root/tedi/alias
WORKDIR /root
ENTRYPOINT ["tail","-f","/dev/null"]
