FROM node:22.13-alpine3.21
RUN apk update
RUN apk add git curl wget screen nano bash openssh autoconf automake libtool build-base
# libssl-dev libpam0g-dev zlib1g-dev dh-autoreconf ssh
RUN cd /root; git clone https://github.com/shellinabox/shellinabox.git && cd shellinabox && autoreconf -i && CFLAGS="-D_GNU_SOURCE -include utmp.h" ./configure --disable-utmp --disable-utmpx && make
COPY entrypoint /entrypoint
RUN chmod a+x /entrypoint
WORKDIR /root
ENTRYPOINT ["/entrypoint"]
