FROM node:6.17.1-slim
RUN npm config set user root -g \
  && cd /root/ && npm install --legacy-peer-deps -g nide
COPY prompt /root/prompt
COPY bashrc /root/.bashrc
COPY alias /root/alias
COPY entrypoint /entrypoint
RUN chmod a+x /entrypoint
ENTRYPOINT ["/entrypoint"]
