FROM node:16-slim
RUN echo "deb http://debian.org buster main contrib non-free \
deb-src http://debian.org buster main contrib non-free \
deb http://debian.org-security buster/updates main contrib non-free \
deb-src http://debian.org-security buster/updates main contrib non-free" \
 > /etc/apt/sources.list
RUN apt-get update && \
    apt-get install --reinstall ca-certificates && \
    update-ca-certificates && \ 
    apt-get update && \
    apt-get install -y \
    build-essential python2 && \
    ln -s /usr/bin/python2 /usr/bin/python
EXPOSE 8080
RUN mkdir /app
WORKDIR /app
#COPY . /app
#RUN npm install
RUN export PYTHON=/usr/bin/python
RUN npm config set user 0
RUN npm config set unsafe-perm true
RUN npm install -g slap@latest --unsafe-perm
CMD ["tail","-f","/dev/null"]