FROM node:17-alpine3.15
RUN apk add --no-cache --virtual .gyp \
    g++ make gcc py3-pip python2 build-base
EXPOSE 8080
RUN mkdir /app
WORKDIR /app
#COPY . /app
#RUN npm install
RUN export PYTHON=/bin/python2
RUN npm config set user 0
RUN npm config set unsafe-perm true
RUN npm install -g slap@latest --unsafe-perm
CMD ["tail","-f","/dev/null"]