FROM node:16
RUN apt-get update
RUN apt-get install -y build-essential
RUN apt-get install -y git curl wget sudo
RUN curl -sL https://raw.githubusercontent.com/slap-editor/slap/master/install.sh | sh
WORKDIR /workspace
ENTRYPOINT ["slap"]
