#!/bin/sh
docker rm -f nodegit
docker run -d --name=nodegit \
  -v /c/Users/docker/nodegit/repos:/root/node_modules/@goldfiction/gqnodegit/repos \
  -p 7005:7005 \
  --restart=unless-stopped \
  nodegit
