FROM mhart/alpine-node:0.12
RUN npm install -g sinopia
#COPY prompt /root/prompt
#COPY bashrc /root/.bashrc
RUN mkdir /root/sinopia
COPY config.yaml /root/sinopia/config.yaml
COPY entrypoint /entrypoint
RUN chmod a+x /entrypoint
WORKDIR /root
ENTRYPOINT ["/entrypoint"]
