#!/bin/sh
docker rm -f calibre-web
docker run -d \
  --name=calibre-web \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=Etc/UTC \
  -p 8083:8083 \
  -v /c/Users/docker/calibreweb/config:/config \
  -v /c/Users/docker/calibreweb/books:/books \
  -v /d/all/ebook:/books2 \
  -v /c/Users/docker/calibreweb/import:/ingest \
  --privileged \
  --restart unless-stopped \
  lscr.io/linuxserver/calibre-web:latest
docker ps | grep calibre
echo calibre-web running


# -e DOCKER_MODS=linuxserver/mods:universal-calibre `#optional` \
