#!/bin/sh
docker rm -f chrome
docker volume create chrome
docker run -d \
  --name=chrome \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=Etc/UTC \
  -p 3300:3000 \
  -p 3301:3001 \
  -p 3302:3389 \
  --security-opt seccomp=unconfined \
  -v chrome:/config \
  --shm-size="1gb" \
  --restart unless-stopped \
  lscr.io/linuxserver/chrome
