#!/bin/sh
docker rm -f msedge
docker run -d \
  --name=msedge \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=Etc/UTC \
  -e EDGE_CLI=https://www.linuxserver.io/ `#optional` \
  -p 3200:3000 \
  -p 3201:3001 \
  -v /c/Users/docker/msedge/config:/config \
  --shm-size="1gb" \
  --restart unless-stopped \
  lscr.io/linuxserver/msedge:latest
