#!/bin/sh
docker rm -f jellyfin
docker run -d --name=jellyfin \
  -v /srv/jellyfin/config:/config \
  -v /srv/jellyfin/cache:/cache \
  -v /c/Users/docker/jellyfin/media:/media \
  --net=host jellyfin/jellyfin:latest

