#!/bin/sh
docker rm -f mstream
docker run -d \
  --name=mstream \
  --memory=512m \
  --cpus=".75" \
  -e PUID=1000 \
  -e PGID=1000 \
  -e USER=admin \
  -e PASSWORD=78567856 \
  -e USE_JSON=true \
  -e TZ=American/Toronto \
  -p 3000:3000 \
  -v /c/Users/docker/mstream/config:/config \
  -v /c/Users/docker/data/music:/music \
  --restart unless-stopped \
  mstream:latest
