#!/bin/sh
docker rm -f slap
docker run -d --name=slap \
  -e SLAP_JWT_SECRET=secret \
  -v /c/Users/vlgx/dev:/home/dev \
  -p 8040:8080 \
  --restart=unless-stopped \
  gosolardevadmin/slap-realtime:git-2a0c08465f39 \
  tail -f /dev/null