FROM node:20.20.2 AS builder
RUN npm install -g stmux

FROM node:20.20.2-slim
COPY --from=builder /usr/local /usr/local
COPY prompt /root/prompt
COPY bashrc /root/.bashrc
COPY entrypoint /entrypoint
WORKDIR /root
ENTRYPOINT ["/entrypoint"]
