FROM node:18.20.8
RUN apt-get update
RUN apt-get install -y git curl wget screen nano bash build-essential
RUN cd /root; git clone https://github.com/goldfiction/gqflowchart.git; cd gqflowchart; npm install
EXPOSE 3443
COPY prompt /root/prompt
COPY bashrc /root/.bashrc
COPY entrypoint /entrypoint
WORKDIR /root
ENTRYPOINT ["tail","-f","/dev/null"]
